project/apps/Historia/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "Historia"

urlpatterns = [
    path("", views.home ,name="home"),
    path("Personaje/list/",views.PersonajeList.as_view(), name = "personaje_list"),
    path("Personaje/create/",views.PersonajeCreate.as_view(), name = "personaje_create"),
    path("Faccion/create/",views.FaccionCreate.as_view(), name = "faccion_create"),
    path("Personaje/detail/<int:pk>",views.PersonajeDetail.as_view(), name = "personaje_detail"),
    path("Personaje/update/<int:pk>",views.PersonajeUpdate.as_view(), name = "personaje_update"),
    path("Personaje/delete/<int:pk>",views.PersonajeDelete.as_view(), name = "personaje_delete"),

]

project/apps/Home/urls.py
from django.urls import path
from .views import home

app_name = "Home"

urlpatterns = [
    path("", home, name="home"),

]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
        path("", include("Home.urls")),
    path("historia/", include("Historia.urls")),
    path("juegos/", include("Juegos.urls")),
    path("libreria/", include("Libreria.urls")),
    path("lugares/", include("Lugares.urls")),
    path("subscribete/", include("Subscripcion.urls")),
    path("series_peliculas/", include("series_peliculas.urls")),

]

project/apps/Historia/models.py
from django.db import models

# Create your models here.
class Faccion(models.Model):
    """Creación de facción del Personaje"""
    nombre = models.CharField(max_length=50,unique=True)

    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        verbose_name = "Facción"
        verbose_name_plural = "Facciones"

class Personaje(models.Model):
    """Creación de un personaje"""
    nombre = models.CharField(max_length=50,unique=True)
    faccion = models.ForeignKey(Faccion,on_delete=models.SET_NULL,null=True, blank=True)
    historia = models.TextField(max_length=1000)

    def __str__(self) -> str:
        return self.nombre
    
    class Meta:
        verbose_name = "Personaje"
        verbose_name_plural = "Personajes"

project/apps/Historia/forms.py
from django import forms

from .models import Personaje, Faccion


class PersonajeForm(forms.ModelForm):
    class Meta:
        model = Personaje
        fields = "__all__"

class FaccionForm(forms.ModelForm):
    class Meta:
        model = Faccion
        fields = "__all__"

project/apps/Historia/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, DetailView, UpdateView
from django.urls import reverse_lazy
from . import forms, models

def home(request):
    query = models.Personaje.objects.all()
    contexto = {"datos_registro":query}
    return render(request,"Historia/index_historia.html",contexto)


#Listar todos los Personajes
class PersonajeList(ListView):  
    model = models.Personaje

#Crear Personaje
class PersonajeCreate(CreateView):
    model = models.Personaje
    form_class = forms.PersonajeForm
    success_url = reverse_lazy("Historia:personaje_list")
    
#Crear Faccion
class FaccionCreate(CreateView):
    model = models.Faccion
    form_class = forms.FaccionForm
    success_url = reverse_lazy("Historia:personaje_create")

#Ver más detalles de Personaje
class PersonajeDetail(DetailView):
    model = models.Personaje

#Actualizar datos de Personaje
class PersonajeUpdate(UpdateView):
    model = models.Personaje
    form_class = forms.PersonajeForm
    success_url = reverse_lazy("Historia:personaje_list")

#Eliminar datos de Personaje
class PersonajeDelete(DeleteView):
    model = models.Personaje
    success_url = reverse_lazy("Historia:personaje_list")

project/apps/Historia/templates/Historia/Faccion_form.html
{% extends 'Home/index_home.html' %}

{% block CONTENIDO %}
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-5">
                            <span class="section-heading-upper">Nueva Facción</span>
                            <span class="section-heading-lower">Ingresa los datos</span>
                        </h2>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">Guardar</button>
                        </form>
                        <br>
                        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Historia:personaje_create' %}">Volver a Crear Personaje</a></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock CONTENIDO %}

project/apps/Historia/templates/Historia/Personaje_confirm_delete.html
{% extends 'Home/index_home.html' %}

{% block CONTENIDO %}

    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">{{ object }}</span>
                            <span class="section-heading-lower">Eliminar Personaje</span>
                        </h2>
                        <p class="mb-0">¿Está seguro que desea eliminar "{{ object }}"?</p>
                        <br>
                        <center>
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Confirmar</button>
                            </form>
                        </center>
                        <br>
                        <center>
                            <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Home:home' %}">Volver a página principal</a></div>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
    
    
{% endblock CONTENIDO %}

project/apps/Historia/templates/Historia/Personaje_detail.html
{% extends 'Home/index_home.html' %}

{% block CONTENIDO %}
    
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">Personaje</span>
                        <span class="section-heading-lower">Detalle</span>
                    </h2>
                    
                        <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                                <li class="list-unstyled-item list-hours-item d-flex">
                                    {{ object.nombre }} 
                                    <span class="ms-auto">{{ object.faccion }}</span>
                                </li>
                        </ul>
                        <p class="address mb-5">
                            <em>
                                {{ object.historia }}
                            </em>
                        </p>
                    
                    
                </div>
            </div>
        </div>
    </div>
    <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Home:home' %}">Ir a página principal</a></div>
</section>

{% endblock CONTENIDO %}

project/apps/Historia/templates/Historia/Personaje_form.html
{% extends 'Home/index_home.html' %}

{% block CONTENIDO %}
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-5">
                            <span class="section-heading-upper">Personaje Nuevo</span>
                            <span class="section-heading-lower">Ingresa los datos</span>
                        </h2>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">Guardar</button>
                        </form>
                        <br>
                        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Historia:faccion_create' %}">Crear Facción</a></div>
                        <br>
                        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Home:home' %}">Volver a página principal</a></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock CONTENIDO %}

project/apps/Historia/templates/Historia/Personaje_list.html
{% extends 'Home/index_home.html' %}

{% block CONTENIDO %}
    
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">Base de Datos</span>
                        <span class="section-heading-lower">Personajes</span>
                    </h2>
                    <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                        {% for object in object_list %}
                            <li class="list-unstyled-item list-hours-item d-flex">
                                {{ object.nombre }}
                                <span class="ms-auto">{{ object.faccion }}</span>
                                <br>
                            </li>
                            <li class="list-unstyled-item list-hours-item d-flex">
                                <div class="intro-button mx-auto" ><a class="btn btn-primary btn-xl"  href="{% url 'Historia:personaje_detail' object.id %}">Ver Detalle</a></div>
                                <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Historia:personaje_update' object.id %}">Actualizar Info</a></div>
                                <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Historia:personaje_delete' object.id %}">Eliminar</a></div>
                            </li>
                                
                            
                        {% endfor %}
                    </ul>
                    <p class="address mb-5">
                        <em>
                            <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Historia:personaje_create' %}">Crear Nuevo Personaje</a></div>
                        </em>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock CONTENIDO %}

project/apps/Historia/templates/Historia/index_historia.html
{% extends 'Home/index_home.html' %}
{% load static %}

{% block CONTENIDO %}

    <section class="page-section about-heading">
    <div class="container"><center>
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'Home/assets/img/personajes.jpg' %}" alt="..." /></center>
    </div>
    </section>

    {% for datito in datos_registro %}
        <section>
            <div class="about-heading-content">
                <div class="row">
                    <div class="col-xl-9 col-lg-10 mx-auto">
                        <div class="bg-faded rounded h1-5">
                            <h2 class="section-heading mb-4">
                                <span class="section-heading-upper"><br>{{ datito.faccion }}</span>
                                <span class="section-heading-lower">{{ datito.nombre }}</span>
                            </h2>
                            <p> {{ datito.historia }}<br> </p> 
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <div></div>
    {% endfor %}
    <br>
    <center>
        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Historia:personaje_list' %}">Ver lista Personajes</a></div>
    </center>
<br>

{% endblock CONTENIDO %}