project/apps/Subscripcion/urls.py
from django.urls import path
from .views import home, subscriptores

app_name = "Subscripcion"

urlpatterns = [
    path("", home, name="home"),
    path("SUBSCRIPCIONES/",subscriptores, name="subscriptores")

]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
        path("", include("Home.urls")),
    path("historia/", include("Historia.urls")),
    path("juegos/", include("Juegos.urls")),
    path("libreria/", include("Libreria.urls")),
    path("lugares/", include("Lugares.urls")),
    path("subscribete/", include("Subscripcion.urls")),
    path("series_peliculas/", include("series_peliculas.urls")),

]

project/apps/Subscripcion/models.py
from django.db import models

# Create your models here.

class Subscribete(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    correo = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.correo}"
    
    class Meta:
        verbose_name = "Subscripción"
        verbose_name_plural = "Subscripciones"

project/apps/Subscripcion/forms.py
from django import forms

from .models import Subscribete


class SubscribirForm(forms.ModelForm):
    class Meta:
        model = Subscribete
        fields = ["nombre", "apellido", "correo"]

project/apps/Subscripcion/views.py
from django.shortcuts import render, redirect
from .models import Subscribete
from .forms import SubscribirForm

# Acceso a formulario de subscripción
def home(request):
    if request.method == "POST":
        form = SubscribirForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Home:home")
    else:  # request.method == "GET"
        form = SubscribirForm()
    return render(request, "Subscripcion/formulario.html",{"form": form})

#Muestra los subscripciones guardadas
def subscriptores(request):
    registro_subscripcion = Subscribete.objects.all()
    contexto_subs = {"Subscriptores":registro_subscripcion}
    return render(request,"Subscripcion/index_subscripcion.html",contexto_subs)

project/apps/Subscripcion/templates/Subscripcion/formulario.html
{% extends 'Home/index_home.html' %}

{% block CONTENIDO %}
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-5">
                            <span class="section-heading-upper">¡Subscríbete!</span>
                            <span class="section-heading-lower">Ingresa tus datos</span>
                        </h2>
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">Guardar</button>
                        </form>
                        <br>
                        <div class="intro-button mx-auto"><a class="btn btn-primary btn-xl" href="{% url 'Subscripcion:subscriptores' %}">Visualizar Subscriptores</a></div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock CONTENIDO %}

project/apps/Subscripcion/templates/Subscripcion/index_subscripcion.html
{% extends 'Home/index_home.html' %}

{% block CONTENIDO %}
    
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner bg-faded text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">Personas</span>
                        <span class="section-heading-lower">Subscritas</span>
                    </h2>
                    <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                        {% for subscriptor in Subscriptores %}
                            <li class="list-unstyled-item list-hours-item d-flex">
                                {{ subscriptor.nombre }} {{ subscriptor.apellido }}
                                <span class="ms-auto">{{ subscriptor.correo }}</span>
                            </li>
                        {% endfor %}
                    </ul>
                    <p class="address mb-5">
                        <em>
                            <strong>¡No olvides mandar correo a los subscriptores!</strong>
                            <br />
                            Que la fuerza te acompañe
                        </em>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock CONTENIDO %}